#!/bin/sh

numlockx &
setxkbmap -option caps:none se &
wallpaper &

start="dunst dwmblocks mpd mpd-update pa-update"

for process in $start; do
	pidof -x "$process" || "$process" &
done >/dev/null 2>&1
